version: "3.9"

services:
  sd-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: stable-diffusion-studio
    container_name: sd-api
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ../final_outputs:/app/final_outputs
      - ../upscaled_outputs:/app/upscaled_outputs
      - ../scheduler_outputs:/app/scheduler_outputs"
